{{- if not .Values.database.useExternalDB -}}
apiVersion: v1
kind: Secret
metadata:
  name: maestro-db-config
  namespace: '{{ .Values.global.namespace }}'
stringData:
  host: maestro-db.maestro
  port: '5432'
  name: maestro
  user: maestro
  password: {{ randAlphaNum 16 }}
{{- end -}}
