apiVersion: v1
kind: Service
metadata:
  name: maestro-grpc
  namespace: '{{ .Values.global.namespace }}'
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: maestro
