{{- if not .Values.database.useExternalDB -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maestro-db-data
  namespace: '{{ .Values.global.namespace }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}
{{- end -}}
