# Copyright (c) 2025 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

# make base images configurable (overridable for local/CI e2e builds that
# lack credentials for the Red Hat-internal registries used by default)
ARG BASE_IMAGE=brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.26
ARG FINAL_BASE_IMAGE=registry.redhat.io/ubi9/ubi-minimal-pqc:latest

# Stage 1: build the target binaries
FROM ${BASE_IMAGE} AS builder

WORKDIR /workspace
COPY go.sum go.mod ./
COPY ./cmd ./cmd
COPY ./pkg ./pkg

RUN CGO_ENABLED=1 GOFLAGS="-p=4" go build -mod=readonly -tags strictfipsruntime -a -v -o bin/conductor cmd/main.go

# Stage 2: Copy the binaries from the image builder to the base image
FROM ${FINAL_BASE_IMAGE}

# Red Hat annotations.
LABEL com.redhat.component="cloudevents-conductor"
LABEL org.label-schema.vendor="Red Hat"
LABEL org.label-schema.license="Red Hat Advanced Cluster Management for Kubernetes EULA"
LABEL org.label-schema.schema-version="1.0"

# Bundle metadata
LABEL name="multicluster-engine/cloudevents-conductor-rhel9"
LABEL cpe="cpe:/a:redhat:multicluster_engine:5.0::el9"
LABEL summary="multicluster cloudevents conductor"
LABEL io.openshift.expose-services=""
LABEL io.openshift.tags="data,images"
LABEL io.k8s.display-name="multicluster cloudevents conductor"
LABEL io.k8s.description="This is the standard release image for the multicluster cloudevents conductor"
LABEL maintainer="['acm-component-maintainers@redhat.com']"
LABEL description="multicluster cloudevents conductor"

ARG GIT_COMMIT
ENV CONDUCTOR=/server \
  USER_UID=1001 \
  USER_NAME=conductor \
  GIT_COMMIT=${GIT_COMMIT}

# install conductor binary
COPY --from=builder /workspace/bin/conductor ${CONDUCTOR}

USER ${USER_UID}
